# Generated by Django 5.0.2 on 2024-02-26 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFormData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('pancard', models.CharField(blank=True, max_length=100, null=True)),
                ('current_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.BigIntegerField(blank=True, null=True)),
                ('current_knowledge', models.CharField(blank=True, max_length=100, null=True)),
                ('goals', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_tolarance_low', models.DecimalField(decimal_places=2, default=False, max_digits=5)),
                ('risk_tolarance_mid', models.DecimalField(decimal_places=2, default=False, max_digits=5)),
                ('risk_tolarance_high', models.DecimalField(decimal_places=2, default=False, max_digits=5)),
                ('improve', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('annual_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_name', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(max_length=100)),
                ('scheme_type', models.CharField(max_length=100)),
                ('sum_assured', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='dashboard.clientformdata')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('fixed_deposit', models.DecimalField(decimal_places=2, default=False, max_digits=5)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portfolio', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('scheme_name', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='dashboard.clientformdata')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='dashboard.clientformdata')),
            ],
        ),
    ]
