# Generated by Django 5.0 on 2023-12-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='entity_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='event_type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
