# Generated by Django 4.2.9 on 2024-01-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmembers',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
