# Generated by Django 4.2.9 on 2024-02-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_businessmembers_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexdatafromnse',
            old_name='divYield',
            new_name='divyield',
        ),
    ]
