# Generated by Django 4.2.9 on 2024-03-13 14:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_divyield_indexdatafromnse_divyield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='client_portal_enabled',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='user',
        ),
        migrations.AddField(
            model_name='clients',
            name='current_knowledge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='current_occuption',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='emergency_funds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='feedback',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='goals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='clients',
            name='pancard',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='risk_tolerance',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clients',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan', to='dashboard.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('investment_date', models.DateField()),
                ('scheme_name', models.CharField(max_length=100)),
                ('debt_quality', models.CharField(max_length=100)),
                ('fixd_deposit', models.CharField(max_length=100)),
                ('market_value', models.FloatField()),
                ('portfolio', models.FloatField()),
                ('quantity', models.FloatField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='investment', to='dashboard.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('annual_premium', models.FloatField()),
                ('company_name', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(max_length=100)),
                ('scheme_type', models.CharField(max_length=100)),
                ('sum_assured', models.FloatField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurance', to='dashboard.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
