# Generated by Django 4.2.9 on 2024-03-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_family'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
    ]
