# Generated by Django 5.0 on 2024-01-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_indexdatafromnse_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdatafromnse',
            name='date',
            field=models.DateField(),
        ),
    ]
