# Generated by Django 4.2.9 on 2024-03-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_blockedclients_alter_clients_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
