# Generated by Django 4.2.9 on 2024-03-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_clients_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='business_member',
        ),
    ]
