# Generated by Django 4.2.9 on 2024-03-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_clients_business_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='current_occuption',
            new_name='current_occupation',
        ),
    ]
