# Generated by Django 4.2.9 on 2024-03-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_current_occuption_clients_current_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='investment_date',
            new_name='date',
        ),
    ]
