# Generated by Django 4.2.9 on 2024-03-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_investment_date_investment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='debt_quality',
            new_name='debt_quantity',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='fixd_deposit',
            new_name='fixed_deposit',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='amount',
            new_name='invested_amount',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='quantity',
            new_name='share_quantity',
        ),
    ]
