# Generated by Django 4.2.9 on 2024-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_debt_quality_investment_debt_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='debt_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investment',
            name='fixed_deposit',
            field=models.FloatField(),
        ),
    ]
